### ISSUE TITLE
Widok rekrutera

### ISSUE THREAD

**Issue by PawelBialek98** [lodz-university-of-technology-masi/Stratocumulusy#18]

**Comment by PrzemyslawLapinski** [comment]
Po zalogowaniu się jako rekruter pojawia się ten widok.
Proponuję chwilowo takie sekcje/podstrony:
-Kandydatów ( lista obecnych kandydatów, dodawanie kandydatów, usuwanie kandydatów)
-Testy rekrutera ( zarządzanie testami, importowanie testów)
-Sprawdzanie/ocenianie testów

**Comment by PrzemyslawLapinski** [comment]
Został dodany panel sterujący. Łatwo go edytować, żeby dodać sobie nowe widoki.
